### ISSUE TITLE
transport 

### ISSUE THREAD

**Issue by Glimmering-Melon** [XDSenDX/Minecraft-Modpack-Dev#3]
![image](https://github.com/XDSenDX/Minecraft-Modpack-Dev/assets/108012821/02c5b072-bb0c-4c11-a7c4-6e32c375b598)

https://www.curseforge.com/minecraft/mc-mods/laendli-transport

**Comment by XDSenDX** [comment]
cai nay dep co dieu no co guns

**Comment by XDSenDX** [comment]
tuc la mik cx phai xoa lun immersive aircraft

**Comment by XDSenDX** [comment]
Replaced by simple planes and simple cars mod.
